- name: Home Server
  hosts: homeserver
  tasks:
   - name: Update & Upgrade
     become: true
     ansible.builtin.apt:
      update_cache: true
      upgrade: dist
   - name: Podman Install
     become: true
     ansible.builtin.apt:
      name:
       - podman
       - podman-compose
